title:       Audio Controls
lede:        'A simple piece of JavaScript to add YouTube-like keyboard controls to <audio> elements on any page.'
version:     1.1.0
color:       5f8aa6

author:
  name: Chris Burnell
  url:  https://chrisburnell.com

url:      https://audio.chrisburnell.com
baseurl:  ''

timezone: Europe/London
language: en

future: true
incremental: true
destination: ./_site

exclude:
- CNAME
- deploy.sh
- Gemfile
- gulpfile.babel.js
- LICENSE
- node_modules
- package.json
- README.md
- src
- vendor
